export const categories = {
  ar: [
    { id: 'all', name: 'الكل', image: '/images/yes-and-studio-XVYz_QeiEBw-unsplash.jpg' },
    { id: 'chocolates', name: 'شوكولاتة', image: '/images/branden-skeli-CnTdVeDmTaQ-unsplash.jpg' },
    { id: 'biscuits', name: 'بسكويت وسناك', image: '/images/prigles (1).jpg' },
    { id: 'luxury', name: 'حلويات فاخرة', image: '/images/candy (1).jpg' },
    { id: 'beverages', name: 'مشروبات', image: '/images/down (1).png' }
  ],
  en: [
    { id: 'all', name: 'All', image: '/images/yes-and-studio-XVYz_QeiEBw-unsplash.jpg' },
    { id: 'chocolates', name: 'Chocolates', image: '/images/branden-skeli-CnTdVeDmTaQ-unsplash.jpg' },
    { id: 'biscuits', name: 'Biscuits & Snacks', image: '/images/prigles (1).jpg' },
    { id: 'luxury', name: 'Luxury Sweets', image: '/images/candy (1).jpg' },
    { id: 'beverages', name: 'Beverages', image: '/images/down (1).png' }
  ]
};

export const initialProducts = [
  {
    id: 1,
    name: { ar: 'شوكولاتة جالكسي سادة 50 غم', en: 'Galaxy Smooth Chocolate 50g' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '4 ر.س', en: '4 SAR' },
    description: { ar: 'شوكولاتة جالكسي بالحليب الكلاسيكية الناعمة.', en: 'Classic smooth Galaxy milk chocolate.' },
    images: ['/images/yes-and-studio-XVYz_QeiEBw-unsplash.jpg'],
    visible: true,
  },
  {
    id: 2,
    name: { ar: 'سنيكرز بار 50 غم', en: 'Snickers Bar 50g' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '4 ر.س', en: '4 SAR' },
    description: { ar: 'شوكولاتة سنيكرز المحشوة بالكراميل والفول السوداني.', en: 'Snickers chocolate filled with caramel and peanuts.' },
    images: ['/images/branden-skeli-CnTdVeDmTaQ-unsplash.jpg'],
    visible: true,
  },
  {
    id: 3,
    name: { ar: 'تويكس شوكولاتة بالكراميل', en: 'Twix Caramel Chocolate' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '4 ر.س', en: '4 SAR' },
    description: { ar: 'أصابع تويكس المقرمشة مع الكراميل المغطاة بالشوكولاتة.', en: 'Crunchy Twix fingers with caramel covered in chocolate.' },
    images: ['/images/andrii-solok-5BCqrBKDz_A-unsplash.jpg'],
    visible: true,
  },
  {
    id: 4,
    name: { ar: 'كيندر بوينو 43 غم', en: 'Kinder Bueno 43g' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '5 ر.س', en: '5 SAR' },
    description: { ar: 'أصابع ويفر كيندر بوينو الهشة المحشوة بكريمة البندق.', en: 'Crispy Kinder Bueno wafer filled with hazelnut cream.' },
    images: ['/images/amit-lahav-LU_fCezP9-o-unsplash.jpg'],
    visible: true,
  },
  {
    id: 5,
    name: { ar: 'فيريرو روشيه 16 قطعة', en: 'Ferrero Rocher 16 pcs' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '45 ر.س', en: '45 SAR' },
    description: { ar: 'شوكولاتة فيريرو روشيه الفاخرة بالبندق.', en: 'Premium Ferrero Rocher chocolate with hazelnuts.' },
    images: ['/images/abdul-raheem-kannath-K0lBvvsg0wo-unsplash.jpg'],
    visible: true,
  },
  {
    id: 6,
    name: { ar: 'شوكولاتة باتشي الفاخرة 500 غم', en: 'Patchi Luxury Chocolate 500g' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '150 ر.س', en: '150 SAR' },
    description: { ar: 'علبة شوكولاتة باتشي الفاخرة.', en: 'Luxury Patchi chocolate box.' },
    images: ['/images/yes-and-studio-XVYz_QeiEBw-unsplash.jpg'],
    visible: true,
  },
  {
    id: 7,
    name: { ar: 'مارس شوكولاتة 51 غم', en: 'Mars Chocolate 51g' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '4 ر.س', en: '4 SAR' },
    description: { ar: 'شوكولاتة مارس الكلاسيكية بالنوجا والكراميل.', en: 'Classic Mars chocolate with nougat and caramel.' },
    images: ['/images/branden-skeli-CnTdVeDmTaQ-unsplash.jpg'],
    visible: true,
  },
  {
    id: 8,
    name: { ar: 'باونتي جوز الهند 57 غم', en: 'Bounty Coconut 57g' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '4 ر.س', en: '4 SAR' },
    description: { ar: 'شوكولاتة باونتي الغنية بحشوة جوز الهند الطازج.', en: 'Bounty chocolate rich with fresh coconut filling.' },
    images: ['/images/andrii-solok-5BCqrBKDz_A-unsplash.jpg'],
    visible: true,
  },
  {
    id: 9,
    name: { ar: 'كيت كات 4 أصابع', en: 'KitKat 4 Fingers' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '4 ر.س', en: '4 SAR' },
    description: { ar: 'أصابع ويفر كيت كات المقرمشة المغطاة بالشوكولاتة.', en: 'Crunchy KitKat wafer fingers covered in chocolate.' },
    images: ['/images/kitkat.jpg'],
    visible: true,
  },
  {
    id: 10,
    name: { ar: 'مالتيزرز 37 غم', en: 'Maltesers 37g' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '5 ر.س', en: '5 SAR' },
    description: { ar: 'كرات المالتيزرز المقرمشة المغطاة بشوكولاتة الحليب.', en: 'Crunchy Maltesers balls covered in milk chocolate.' },
    images: ['/images/amit-lahav-LU_fCezP9-o-unsplash.jpg'],
    visible: true,
  },
  {
    id: 11,
    name: { ar: 'إم آند إمز فول سوداني', en: 'M&M\'s Peanut' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '5 ر.س', en: '5 SAR' },
    description: { ar: 'حبات إم آند إمز الملونة المحشوة بالفول السوداني.', en: 'Colorful M&M\'s filled with peanuts.' },
    images: ['/images/mnms.jpg'],
    visible: true,
  },
  {
    id: 12,
    name: { ar: 'توبليرون شوكولاتة سويسرية', en: 'Toblerone Swiss Chocolate' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '12 ر.س', en: '12 SAR' },
    description: { ar: 'شوكولاتة توبليرون السويسرية بعسل النحل واللوز.', en: 'Toblerone Swiss chocolate with honey and almonds.' },
    images: ['/images/tobelreon.jpg'],
    visible: true,
  },
  {
    id: 13,
    name: { ar: 'كادبوري ديري ميلك سادة', en: 'Cadbury Dairy Milk' },
    category: { ar: 'شوكولاتة', en: 'Chocolates' },
    price: { ar: '6 ر.س', en: '6 SAR' },
    description: { ar: 'شوكولاتة كادبوري ديري ميلك الكلاسيكية اللذيذة.', en: 'Delicious classic Cadbury Dairy Milk chocolate.' },
    images: ['/images/abdul-raheem-kannath-K0lBvvsg0wo-unsplash.jpg'],
    visible: true,
  },
  {
    id: 14,
    name: { ar: 'برينجلز أحمر أوريجينال 40 غم', en: 'Pringles Original 40g' },
    category: { ar: 'بسكويت وسناك', en: 'Biscuits & Snacks' },
    price: { ar: '5 ر.س', en: '5 SAR' },
    description: { ar: 'شيبس برينجلز الأصلي المقرمش.', en: 'Original crunchy Pringles chips.' },
    images: ['/images/prigles (1).jpg'],
    visible: true,
  },
  {
    id: 15,
    name: { ar: 'برينجلز كريمة وبصل 40 غم', en: 'Pringles Sour Cream & Onion 40g' },
    category: { ar: 'بسكويت وسناك', en: 'Biscuits & Snacks' },
    price: { ar: '5 ر.س', en: '5 SAR' },
    description: { ar: 'شيبس برينجلز بنكهة الكريمة الحامضة والبصل.', en: 'Pringles chips with sour cream and onion flavor.' },
    images: ['/images/prigles (2).jpg'],
    visible: true,
  },
  {
    id: 16,
    name: { ar: 'حلوى جيلي مشكلة', en: 'Mixed Jelly Candy' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '12 ر.س', en: '12 SAR' },
    description: { ar: 'مجموعة متنوعة من حلوى الجيلي بنكهات الفواكه.', en: 'A variety of jelly candies with fruit flavors.' },
    images: ['/images/candy (1).jpg'],
    visible: true,
  },
  {
    id: 17,
    name: { ar: 'حلوى مصاص ملونة', en: 'Colorful Lollipops' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '5 ر.س', en: '5 SAR' },
    description: { ar: 'مصاصات ملونة بنكهات لذيذة يحبها الأطفال.', en: 'Colorful lollipops with delicious flavors kids love.' },
    images: ['/images/candy (2).jpg'],
    visible: true,
  },
  {
    id: 18,
    name: { ar: 'مارشميلو ناعم', en: 'Soft Marshmallow' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '8 ر.س', en: '8 SAR' },
    description: { ar: 'قطع مارشميلو هشة وناعمة تذوب في الفم.', en: 'Soft and fluffy marshmallow pieces that melt in your mouth.' },
    images: ['/images/candy (3).jpg'],
    visible: true,
  },
  {
    id: 19,
    name: { ar: 'حلوى كراميل قديمة', en: 'Old Fashioned Caramel' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '15 ر.س', en: '15 SAR' },
    description: { ar: 'حلوى الكراميل التقليدية الغنية بالزبدة.', en: 'Traditional butter-rich caramel candy.' },
    images: ['/images/candy (4).jpg'],
    visible: true,
  },
  {
    id: 20,
    name: { ar: 'حلوى فواكه مجففة', en: 'Dried Fruit Candy' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '20 ر.س', en: '20 SAR' },
    description: { ar: 'حلوى مصنوعة من قطع الفواكه الطبيعية المجففة.', en: 'Candy made from natural dried fruit pieces.' },
    images: ['/images/candy (5).jpg'],
    visible: true,
  },
  {
    id: 21,
    name: { ar: 'علكة فقاعات ملونة', en: 'Colorful Bubble Gum' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '3 ر.س', en: '3 SAR' },
    description: { ar: 'علكة فقاعات كلاسيكية بنكهات متنوعة.', en: 'Classic bubble gum in various flavors.' },
    images: ['/images/candy (6).jpg'],
    visible: true,
  },
  {
    id: 22,
    name: { ar: 'حلوى حمضية', en: 'Sour Candy' },
    category: { ar: 'حلويات فاخرة', en: 'Luxury Sweets' },
    price: { ar: '7 ر.س', en: '7 SAR' },
    description: { ar: 'حلوى مغطاة بطبقة من السكر الحامض المنعش.', en: 'Candy coated with a refreshing layer of sour sugar.' },
    images: ['/images/candy (7).jpg'],
    visible: true,
  },
  {
    id: 23,
    name: { ar: 'مشروب غازي منعش', en: 'Refreshing Soft Drink' },
    category: { ar: 'مشروبات', en: 'Beverages' },
    price: { ar: '3 ر.س', en: '3 SAR' },
    description: { ar: 'مشروب غازي بارد ومنعش.', en: 'Cool and refreshing soft drink.' },
    images: ['/images/down (1).png'],
    visible: true,
  },
  {
    id: 24,
    name: { ar: 'عصير طبيعي', en: 'Natural Juice' },
    category: { ar: 'مشروبات', en: 'Beverages' },
    price: { ar: '8 ر.س', en: '8 SAR' },
    description: { ar: 'عصير فواكه طبيعي 100% بدون سكر مضاف.', en: '100% natural fruit juice with no added sugar.' },
    images: ['/images/down (2).png'],
    visible: true,
  },
  {
    id: 25,
    name: { ar: 'مياه معدنية فاخرة', en: 'Premium Mineral Water' },
    category: { ar: 'مشروبات', en: 'Beverages' },
    price: { ar: '2 ر.س', en: '2 SAR' },
    description: { ar: 'مياه معدنية نقية من ينابيع طبيعية.', en: 'Pure mineral water from natural springs.' },
    images: ['/images/down (3).png'],
    visible: true,
  }
];
